name: "debug commands"
on: [push]
jobs:
  more_on_jobs_1:
    runs-on: ubuntu-latest
    steps:
    - name: "Normal Text"
      run: echo "Normal Text"

    - name: "error Text"
      run: echo "::error Error missing something"

    - name: "error Text 2"
      run: echo "::error title=error,file=app.js,line=2,endLine=3,col=5,endColumn=20 Missing something"

    # - name: "Normal Text"
    #   run: echo "Normal Text"
    # - name: "Normal Text"
    #   run: echo "Normal Text"
      
