name: expressions-workflow
on:
  push:

jobs:
  env_demo_job:
    env:
        MY_ENV_VAR: ${{ github.ref == 'feature/adding-a-new-feature'  }}
    runs-on: ubuntu-latest
    concurrency:
      group: concurrency-group
      cancel-in-progress: true

    name: Expressions Demo
    steps:
      - name: Value of MY_ENV_VAR
        run: 
          echo "Value of MY_ENV_VAR is ${{ env.MY_ENV_VAR }}"
    
      - name: Run Step for main branch
        if: github.ref == 'ref/heads/main'
        run:  echo "from main"
    
      - name: Run Step for not main branch
        if: github.ref != 'ref/heads/main'
        run:  echo "not main"