name: expressions-workflow
on:
  push:

jobs:
  env_demo_job_1:
    name: Environment Job 1 is executed
    if: github.ref == 'refs/heads/main'
    env:
        MY_ENV_VAR: ${{ github.ref == 'feature/adding-a-new-feature'  }}
    runs-on: ubuntu-latest
    concurrency:
      group: concurrency-group
      cancel-in-progress: true

    steps:
      - name: Value of MY_ENV_VAR
        run: 
          echo "Value of MY_ENV_VAR is ${{ env.MY_ENV_VAR }}"
          print ${{ github.ref }}
    
      - name: Run Step for main branch
        if: github.ref == 'refs/heads/main'
        run:  echo "from main"
    
      - name: Run Step for not main branch
        if: github.ref != 'refs/heads/main'
        run:  echo "not main"
  env_demo_job_2:
    name: Environment Job 2 is executed
    if: github.ref != 'refs/heads/main'
    env:
        MY_ENV_VAR: ${{ github.ref == 'feature/adding-a-new-feature'  }}
    runs-on: ubuntu-latest
    concurrency:
      group: concurrency-group
      cancel-in-progress: true

    steps:
      - name: Value of MY_ENV_VAR
        run: 
          echo "Value of MY_ENV_VAR is ${{ env.MY_ENV_VAR }}"
          print ${{ github.ref }}
    
      - name: Run Step for main branch
        if: github.ref == 'refs/heads/main'
        run:  echo "from main"
    
      - name: Run Step for not main branch
        if: github.ref != 'refs/heads/main'
        run:  echo "not main"