name: matrix-demo-workflow
on:
  push: 

jobs:
  # env_demo_job:
  #   runs-on: ubuntu-latest
  #   concurrency:
  #     group: concurrency-group
  #     cancel-in-progress: true

  #   name: Matrix Demo
  #   steps:
  #     - name: Print Docker Info
  #       run: 
  #         docker info
      
  #     - name: Run Image
  #       run:
  #         docker run hello-world
      
  #     - name: Check Container
  #       run:
  #         docker container ls --all
  env_demo_job:
    strategy:
     matrix:
       os: [ubuntu-latest, windows-latest]
       images: [hello-world, busybox, nginx]
       exclude:
         - images: nginx
           os: windows-latest
    runs-on: ${{ matrix.os }}
    

    name: Matrix Demo
    steps:
      - name: Print Docker Info
        run: 
          docker info
      
      - name: Running ${{ matrix.images }} on ${{ matrix.os }}
        run:
          docker run ${{ matrix.images }}
      
      - name: Check Container
        run:
          docker container ls --all