name: 'My First Workflow'

on: push

jobs:

    print_job:
        name: Print Echoes
        runs-on: ubuntu-latest

        steps:
            - name: Print the echo statements
              run: echo "hello world"


