name: my-second-workflow
on:
  push

jobs:
  env_demo_job:
    runs-on: ubuntu-latest
    # env:
    #   USERNAME: "myuser"
    #   PASSWORD: "mysecretpassword"
    
    name: Environment Demo
    steps:
      - name: env variables
        # env:
        #   USERNAME: "myuser"
        #   PASSWORD: "mysecretpassword"
        run: |
          echo ${{ vars.USERNAME }}
      
      - name: print USERNAME again
        run: 
          echo $USERNAME
      
      - name: print PASSWORD 
        run:
          echo ${{ secrets.USERPASSWORD }}